### ISSUE TITLE
copy is not a Function

### ISSUE THREAD

**Issue by kcollignon** [lazybensch/ember-cli-copyable#12]
Hello,

I am trying to copy a model object and am getting the error, `format.copy is not a Function`. Any ideas what I am doing wrong? Here is my controller with my action from a form:

``` coffeescript
`import Notify from 'ember-notify'`
`import Copyable from 'ember-cli-copyable'`

DocumentFormatCopyController = Ember.Controller.extend
  needs: ['application']
  copiedName: null

  actions:
    cancel: ->
      @transitionToRoute 'document_formats'
    copyFormat: ->
      newName = @get('copiedName')
      format = @get('model')
      format.copy({name: newName}).then (copy) =>
        Notify.success('Saved!')
        @transitionToRoute 'document_format', copy

`export default DocumentFormatCopyController`
```

**Comment by pgasiorowski** [comment]
Depending on your customizations in route.afterModel the model might be a Promise? I'd try:
`@get.('model').then((format) => format.copy())`
or not extending the Format model with the Copyable mixin?
`export default DS.Model.extend Copyable`

**Comment by lazybensch** [comment]
yah, it is probably, as @WooDzu mentioned, that you have forgotten to extend your model like this:

``` coffee
`import Copyable from 'ember-cli-copyable'`

FormatModel = EmberModel.extend Copyable
```

**Comment by kcollignon** [comment]
@WooDzu @lazybensch thank you! You are correct, the model was not extending Copyable.
